// Constants

export const TECH = {
  C: 'C',
  CPP: 'C++',
  CSHARP: 'C#',
  PYTHON: 'Python',
  JS: 'Javascript',
  TS: 'Typescript',
  HTML: 'HTML',
  CSS: 'CSS',
  JAVA: 'Java',
  RUST: 'Rust',
  SQL: 'SQL',
  GQL: 'GraphQL',
  GLSL: 'GLSL',
  OPENGL: 'OpenGL',
  WEBGL: 'WebGL',
  ANGULAR: 'Angular',
  REACT: 'React',
  RN: 'React Native',
  UE: 'UnityEngine',
  SWING: 'Java Swing',
  JDBC: 'JDBC',
  TFLOW: 'TensorFlow',
  FLASK: 'Flask',
  NODE: 'Node.js',
  AWS: 'AWS',
  AWS_COGNITO: 'AWS Cognito',
  AWS_APPSYNC: 'AWS AppSync',
  AWS_DB: 'AWS DynamoDB',
  FB: 'Firebase',
  FB_FIRESTORE: 'Firebase Cloud Firestore',
  FB_AUTH: 'Firebase Authentication',
  MONGO: 'MongoDB',
  ORACLE: 'Oracle Database',
  TK: 'Tkinter',
  VSC: 'VSCode API',
}

export const TAGS = {
  ...TECH,
  WEB: 'web app',
  DESKTOP: 'desktop app',
  GP: 'graphics programming',
  G: 'graphics',
  THREED: '3D',
  GAME: 'game',
  DBMS: 'DBMS',
  DB: 'database',
  IR: 'information retrieval',
  OOP: 'object-oriented programming',
  FUNC: 'functional programming',
  SCRIPT: 'scripting',
  ML: 'ML',
  CV: 'computer vision',
  PACKAGE: 'package',
  EXT: 'extension',
  FB: 'Firebase',
  AWS: 'AWS',
  SERVERLESS: 'serverless',
}