// Constants

export const TECH = {
  C: 'C',
  CPP: 'C++',
  CSHARP: 'C#',
  PYTHON: 'Python',
  JS: 'Javascript',
  TS: 'Typescript',
  HTML: 'HTML',
  CSS: 'CSS',
  JAVA: 'Java',
  RUST: 'Rust',
  SQL: 'SQL',
  GQL: 'GraphQL',
  GLSL: 'GLSL',
  OPENGL: 'OpenGL',
  WEBGL: 'WebGL',
  ANGULAR: 'Angular',
  REACT: 'React',
  RN: 'React Native',
  UE: 'UnityEngine',
  SWING: 'Java Swing',
  JDBC: 'JDBC',
  TFLOW: 'TensorFlow',
  FLASK: 'Flask',
  NODE: 'Node.js',
  AWS_COGNITO: 'AWS Cognito',
  AWS_APPSYNC: 'AWS AppSync',
  AWS_DB: 'AWS DynamoDB',
  FB_FIRESTORE: 'Firebase Cloud Firestore',
  FB_AUTH: 'Firebase Authentication',
  MONGO: 'MongoDB',
  ORACLE: 'Oracle Database',
  TK: 'Tkinter',
  VSC: 'VSCode API',
}
