import { ProjectItem } from "../reusable-components/types";
import { TECH } from "../reusable-components/constants";


const data: ProjectItem[] = [
  {
    title: 'Traccio',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.ANGULAR, TECH.TS, TECH.FB_FIRESTORE, TECH.FB_AUTH, TECH.GQL ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'Interactive 3D Modeller',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JS, TECH.WEBGL, TECH.GLSL, TECH.HTML, TECH.CSS ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'Terra Pizza (Game)',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.CSHARP, TECH.UE, ],
    mode: 'solo',
    openSource: false,
    tags: [],
  },
  {
    title: 'HELIOS DBMS',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JAVA, TECH.JDBC, TECH.SQL, TECH.SWING ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'Graphic Design Portfolio',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.REACT, TECH.JS, TECH.CSS, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'Text-Generating RNN',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.PYTHON, TECH.TFLOW, ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'Snake Game',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.PYTHON, TECH.TK, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'Terra Pizza (Website)',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.ANGULAR, TECH.TS, TECH.CSS, TECH.HTML, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: '3D City Modeller',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.C, TECH.OPENGL, ],
    mode: 'solo',
    openSource: false,
    tags: [],
  },
  {
    title: '3D Shooting Drone (Game)',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.CPP, TECH.OPENGL, TECH.GLSL, ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'Distributed Servers Application',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JAVA, ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'Dark Mode (Extension)',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JS, TECH.HTML, TECH.CSS, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'Information Retrieval System',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.PYTHON, ],
    mode: 'solo',
    openSource: false,
    tags: [],
  },
  {
    title: 'Timeline (NPM Package)',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.TS, TECH.ANGULAR, TECH.REACT, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'VSCode Extension',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.TS, TECH.VSC, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
]


export default data;