import { ProjectItem } from "../reusable-components/types";
import { TECH, TAGS } from "../reusable-components/constants";


const data: ProjectItem[] = [
  {
    title: 'Traccio',
    excerpt: 'Job-search tracking application',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.ANGULAR, TECH.TS, TECH.FB, TECH.FB_FIRESTORE, TECH.FB_AUTH, TECH.GQL ],
    mode: 'solo',
    openSource: true,
    tags: [TAGS.WEB, TAGS.FB, TAGS.SERVERLESS, ],
  },
  {
    title: 'Interactive 3D Modeller',
    excerpt: 'Simple, interactive, 3D modelling application',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JS, TECH.WEBGL, TECH.GLSL, TECH.HTML, TECH.CSS ],
    mode: 'solo',
    openSource: true,
    tags: [TAGS.GP, TAGS.WEB, ],
  },
  {
    title: 'Terra Pizza (Game)',
    excerpt: 'Desktop pizza-making game',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.CSHARP, TECH.UE, ],
    mode: 'solo',
    openSource: false,
    tags: [],
  },
  {
    title: 'HELIOS DBMS',
    excerpt: 'Graphical interface database management system',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JAVA, TECH.JDBC, TECH.SQL, TECH.SWING ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'Graphic Design Portfolio',
    excerpt: 'Web-page of a collection of logo and business card designs',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.REACT, TECH.JS, TECH.CSS, ],
    mode: 'solo',
    openSource: true,
    tags: [TAGS.REACT, TAGS.JS, TAGS.CSS, ],
  },
  {
    title: 'Text-Generating RNN',
    excerpt: 'Recurrent Neural Network generating phone reviews',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.PYTHON, TECH.TFLOW, ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'Snake (Game)',
    excerpt: 'SNAAAKE!',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.PYTHON, TECH.TK, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'Terra Pizza (Website)',
    excerpt: 'Website for Terra Pizza (the game)',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.ANGULAR, TECH.TS, TECH.CSS, TECH.HTML, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: '3D City Modeller',
    excerpt: 'Simple building-modelling desktop application',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.C, TECH.OPENGL, ],
    mode: 'solo',
    openSource: false,
    tags: [],
  },
  {
    title: '3D Shooting Drone (Game)',
    excerpt: 'Simple user-controlled drone game',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.CPP, TECH.OPENGL, TECH.GLSL, ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'P2P File-Sharing Application',
    excerpt: 'File-sharing application using distributed directory server pool',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JAVA, ],
    mode: 'team',
    openSource: false,
    tags: [],
  },
  {
    title: 'Dark Mode (Extension)',
    excerpt: 'Dark-mode browser extension',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.JS, TECH.HTML, TECH.CSS, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'IR System',
    excerpt: 'Information retrieval system on benchmark dataset',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.PYTHON, ],
    mode: 'solo',
    openSource: false,
    tags: [],
  },
  {
    title: 'Timeline (NPM Package)',
    excerpt: 'Frontend library for timeline visualization',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.TS, TECH.ANGULAR, TECH.REACT, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
  {
    title: 'VSCode Extension',
    excerpt: 'bleep bloop',
    description: '',
    media: [require('../assets/placeholder_media.png')],
    tech: [TECH.TS, TECH.VSC, ],
    mode: 'solo',
    openSource: true,
    tags: [],
  },
]


export default data;